version: "3.8"

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: formation_manager_saas-php
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            - database

    nginx:
        image: nginx:alpine
        container_name: formation_manager_saas-nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    database:
        image: postgres:16
        container_name: formation_manager_saas-db
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: symfony
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
